//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.WebApplication.ServiceReferenceCalculator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalculator.WebServiceCalculatorSoap")]
    public interface WebServiceCalculatorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse HelloWorld(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse> HelloWorldAsync(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int firtNumber, int lastNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int firtNumber, int lastNumber);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCalculationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse GetCalculations(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse> GetCalculationsAsync(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculations", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequestBody Body;
        
        public GetCalculationsRequest() {
        }
        
        public GetCalculationsRequest(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationsRequestBody {
        
        public GetCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponseBody Body;
        
        public GetCalculationsResponse() {
        }
        
        public GetCalculationsResponse(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.WebApplication.ServiceReferenceCalculator.ArrayOfString GetCalculationsResult;
        
        public GetCalculationsResponseBody() {
        }
        
        public GetCalculationsResponseBody(WebServices.WebApplication.ServiceReferenceCalculator.ArrayOfString GetCalculationsResult) {
            this.GetCalculationsResult = GetCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculatorSoapChannel : WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculatorSoapClient : System.ServiceModel.ClientBase<WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap>, WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap {
        
        public WebServiceCalculatorSoapClient() {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap.HelloWorld(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest inValue = new WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest();
            inValue.Body = new WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequestBody();
            WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse retVal = ((WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse> WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap.HelloWorldAsync(WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldResponse> HelloWorldAsync() {
            WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest inValue = new WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequest();
            inValue.Body = new WebServices.WebApplication.ServiceReferenceCalculator.HelloWorldRequestBody();
            return ((WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int firtNumber, int lastNumber) {
            return base.Channel.Add(firtNumber, lastNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int firtNumber, int lastNumber) {
            return base.Channel.AddAsync(firtNumber, lastNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap.GetCalculations(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest request) {
            return base.Channel.GetCalculations(request);
        }
        
        public WebServices.WebApplication.ServiceReferenceCalculator.ArrayOfString GetCalculations() {
            WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest inValue = new WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest();
            inValue.Body = new WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequestBody();
            WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse retVal = ((WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).GetCalculations(inValue);
            return retVal.Body.GetCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse> WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap.GetCalculationsAsync(WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest request) {
            return base.Channel.GetCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsResponse> GetCalculationsAsync() {
            WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest inValue = new WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequest();
            inValue.Body = new WebServices.WebApplication.ServiceReferenceCalculator.GetCalculationsRequestBody();
            return ((WebServices.WebApplication.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).GetCalculationsAsync(inValue);
        }
    }
}
